repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: python -m ruff check
        language: system
        types: [python]
      - id: mypy_cli
        name: Mypy CLI
        entry: python -m mypy cli/src/boardgames_cli
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy_api
        name: Mypy API
        entry: python -m mypy backend/src/boardgames_api
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: Pytest
        entry: pytest
        language: system
        pass_filenames: false
